myblog-on-ruby-on-rails/config/routes.rb
Myblog::Application.routes.draw do
  root :to => "posts#index"
  get '/search', :to => 'posts#index', :as => :search
  match '/signup', :to => 'users#new'
  match '/login',  :to => 'sessions#new'
  match '/logout', :to => 'sessions#destroy', :via => :delete  
  resources :sessions, :only => [:new, :create, :destroy]
  resources :users, :except => [:index]
  resources :blogs, :except => [:index, :show]
  resources :posts, :only => [:new, :create] do
    resources :comments, :only => [:create, :destroy]
  end
  delete '/:user_name/:post_permalink', :to => 'posts#destroy', :as => :delete_post
  get '/:user_name/:post_permalink', :to => 'posts#show', :as => :post
  get '/:user_name/:post_permalink/edit', :to => 'posts#edit', :as => :edit_post
  put '/:user_name/:post_permalink', :to => 'posts#update', :as => :post
  get '/:user_name/', :to => 'posts#user_name_index', :as => :user_posts  
  get '/users/password/:id', :to => 'users#new_password', :as => :new_password_user
  put '/users/password/:id', :to => 'users#update_password', :as => :update_password_user
end

myblog-on-ruby-on-rails/app/views/layouts/_header.html.erb
<div id='header'>
  <h1> <%= link_to 'MyBlog', search_path  %></h1>
  <%= form_tag search_path, :method => 'get' do %>
    <p>
      <%= text_field_tag :search, params[:search] %>
      <%= submit_tag "Search", :name => nil %>
    </p>
  <% end %>
  <ul>
    <% if signed_in?%>
      <li> Hello <%= current_user.name %> <%= link_to 'Sign out', logout_path, :method => 'delete' %></li>
      <li> <%= link_to 'Profile', user_path(current_user) %></li>
      <li> <%= link_to 'Update profile', edit_user_path(current_user) %></li>
      <% if current_user.blog %>
        <li> <%= link_to 'New post', new_post_path() %> </li>
        <li> <%= link_to 'My blog', user_posts_path(current_user.name) %></li>
        <li> <%= link_to 'Edit blog information', edit_blog_path('blog') %></li>
      <% else %>
        <li> You haven't created your blog, </li>
        <li><%= link_to 'Create the blog', new_blog_path %> </li>
      <% end %>
    <% else %>
      <li><%= link_to 'Signin', login_path %></li>
      <li><%= link_to 'Signup', signup_path %></li>
    <% end %>
  </ul>
</div>

myblog-on-ruby-on-rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title)%>Myblog</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>  
<% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
<% end %>
<%= yield %>
</body>
</html>