myblog-on-ruby-on-rails/config/routes.rb
Myblog::Application.routes.draw do
  root :to => "posts#index"
  get '/search', :to => 'posts#index', :as => :search
  match '/signup', :to => 'users#new'
  match '/login',  :to => 'sessions#new'
  match '/logout', :to => 'sessions#destroy', :via => :delete  
  resources :sessions, :only => [:new, :create, :destroy]
  resources :users, :except => [:index]
  resources :blogs, :except => [:index, :show]
  resources :posts, :only => [:new, :create] do
    resources :comments, :only => [:create, :destroy]
  end
  delete '/:user_name/:post_permalink', :to => 'posts#destroy', :as => :delete_post
  get '/:user_name/:post_permalink', :to => 'posts#show', :as => :post
  get '/:user_name/:post_permalink/edit', :to => 'posts#edit', :as => :edit_post
  put '/:user_name/:post_permalink', :to => 'posts#update', :as => :post
  get '/:user_name/', :to => 'posts#user_name_index', :as => :user_posts  
  get '/users/password/:id', :to => 'users#new_password', :as => :new_password_user
  put '/users/password/:id', :to => 'users#update_password', :as => :update_password_user
end

myblog-on-ruby-on-rails/app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name, :password, :password_confirmation, :website, :avatar
  attr_accessor :check_password
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  has_one :blog, :dependent => :destroy
  has_many :comments, :dependent => :nullify
  has_secure_password
  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token
  validates :name, :presence => true, :length => { :maximum =>50 }, :uniqueness => { :case_sensitive => false }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, :presence => true,
                    :format  =>  { :with => VALID_EMAIL_REGEX },
                    :uniqueness => { :case_sensitive => false }
  validates :password, :presence => true,
                        :length => { :minimum => 6 } ,
                        :confirmation => true, :if => :check_password
  private
    def create_remember_token
      self.remember_token = SecureRandom.base64.tr("+/", "-_")
    end
end

myblog-on-ruby-on-rails/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user, :only => [:edit, :update, :destroy, :update_password, :new_password]
  def show
    @user = User.find(params[:id])
  end
  def new
    @user = User.new
  end
  def create
    @user = User.new(params[:user])
    @user.check_password = true
    if @user.save
      sign_in @user
      flash[:success] = "Now you can create your blog!"
      @blog = @user.build_blog
      render 'blogs/new'
    else
      render "new"
    end
  end
  def update
    @user = User.find(current_user.id)
    if @user.update_attributes(params[:user])
      sign_in @user
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end 
  end
  def update_password
    @user = User.find(current_user.id)
    if @user.authenticate(params[:current_password])
      @user.check_password = true
      puts params[:user].to_s
      if @user.update_attributes(params[:user])
        sign_in @user
        flash.now[:success] = "Password changed"
        render 'show'
      else
        render 'new_password'
      end
    else
      flash[:error] = "Wrong password"
      render 'new_password'
    end
  end
  def new_password
    @user = User.find(params[:id])
  end
  def edit
    @user = User.find(current_user.id)
  end
  def destroy
    @user = User.find(current_user.id)
    #sets all comments information
    @user.comments.each{|comment|
      comment.author = @user.name
      comment.website = @user.website
      comment.email = @user.email
      comment.save
      }
    #end set all comments information
    @user.destroy
    redirect_to root_path, :notice => 'Your account has been successfully removed'
  end
end

myblog-on-ruby-on-rails/app/helpers/users_helper.rb
module UsersHelper
end

myblog-on-ruby-on-rails/app/views/users/edit.html.erb
<h1> Edit page </h1><%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2> Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %> 
  </p>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %> 
  </p>
  <p>
    <%= f.label :website %><br />
    <%= f.text_field :website %>
  </p>  <p>
    <%= f.label :avatar %><br />
    <%= f.file_field :avatar %>
  </p><%= link_to 'Change password', new_password_user_path(@user) %>
  <p class="button"><%= f.submit %></p>
<% end %>
<%= form_tag user_path(@user), :method => :delete    do %>
  <%= submit_tag "Delete account", :confirm => 'Do you really want to delete your account?' %>
<% end %>

myblog-on-ruby-on-rails/app/views/users/new.html.erb
<h1>Sign up</h1>
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2> Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %> 
  </p>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %> 
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %> 
  </p>
  <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p class="button"><%= f.submit %></p>
<% end %>

myblog-on-ruby-on-rails/app/views/users/new_password.html.erb
<h1>Change password</h1>
<%= form_for @user, :url => update_password_user_path(@user), :method => :put do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2> Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
   <%= label_tag :current_password, 'Your current password' %> <br />
   <%= password_field_tag :current_password %>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %> 
  </p>
  <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p class="button"><%= f.submit 'Change password' %></p>
<% end %>

myblog-on-ruby-on-rails/app/views/users/show.html.erb
<p>
  Name: <%= @user.name %>
</p>
<p>
  Email: <%= @user.email %>
</p>
<p>
  Website: <%= @user.website %>
</p>
<p>
  <%= image_tag @user.avatar.url(:thumb) %>
</p>